export interface ICuratedLearningResource {
  resourceId: string;
  title: string;
  description: string;
  url: string;
  provider: string;
  type: string;
  thumbnail?: string;
  channel?: string;
  careerIds: string[];
  skills: string[];
  educationLevels: string[];
  topicCategory: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced' | 'All Levels';
  duration?: string;
  tags: string[];
}

export const CURATED_LEARNING_RESOURCES: ICuratedLearningResource[] = [
  // ─── 1. COMPUTER SCIENCE & SOFTWARE ENGINEERING ─────────────────────────────
  {
    resourceId: 'rfscVS0vtbw',
    title: 'Python for Beginners — Full Course [Programming Tutorial]',
    description: 'Comprehensive Python tutorial covering syntax, variables, data types, control flow, functions, loops, and object-oriented programming concepts.',
    url: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
    provider: 'freeCodeCamp',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/rfscVS0vtbw/maxresdefault.jpg',
    channel: 'freeCodeCamp.org',
    careerIds: ['software_engineer', 'data_scientist', 'ai_engineer', 'ml_engineer'],
    skills: ['Python', 'Programming', 'Problem Solving'],
    educationLevels: ['school', 'intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Computer Science & Software',
    difficulty: 'Beginner',
    duration: '4 hours 26 mins',
    tags: ['python', 'programming', 'basics', 'coding']
  },
  {
    resourceId: '8hly31xKli0',
    title: 'Algorithms and Data Structures Tutorial — Full Course for Beginners',
    description: 'Learn Data Structures (Arrays, Linked Lists, Stacks, Queues, Trees, Graphs) and core algorithms (Binary Search, Merge Sort, Recursion) with practical analysis.',
    url: 'https://www.youtube.com/watch?v=8hly31xKli0',
    provider: 'freeCodeCamp',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/8hly31xKli0/maxresdefault.jpg',
    channel: 'freeCodeCamp.org',
    careerIds: ['software_engineer', 'data_scientist', 'ai_engineer'],
    skills: ['Data Structures', 'Algorithms', 'Problem Solving'],
    educationLevels: ['intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Computer Science & Software',
    difficulty: 'Intermediate',
    duration: '5 hours 22 mins',
    tags: ['dsa', 'data structures', 'algorithms', 'cs']
  },
  {
    resourceId: 'bMknfKXIFA8',
    title: 'React Course — Beginner\'s Tutorial for React JavaScript Library',
    description: 'Learn modern React with Hooks, Component Architecture, State Management, Props, Event Handling, and API integration.',
    url: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
    provider: 'freeCodeCamp',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/bMknfKXIFA8/maxresdefault.jpg',
    channel: 'freeCodeCamp.org',
    careerIds: ['software_engineer', 'ui_designer'],
    skills: ['React', 'JavaScript', 'Web Development'],
    educationLevels: ['diploma', 'undergraduate'],
    topicCategory: 'Computer Science & Software',
    difficulty: 'Intermediate',
    duration: '11 hours 55 mins',
    tags: ['react', 'frontend', 'javascript', 'web dev']
  },
  {
    resourceId: 'RGOj5yH7evk',
    title: 'Git and GitHub for Beginners — Crash Course',
    description: 'Complete hands-on guide to Version Control, Git repository initialization, staging, commits, branches, merges, rebases, and remote GitHub workflows.',
    url: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    provider: 'freeCodeCamp',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/RGOj5yH7evk/maxresdefault.jpg',
    channel: 'freeCodeCamp.org',
    careerIds: ['software_engineer', 'data_scientist', 'ai_engineer', 'cloud_engineer'],
    skills: ['Git', 'Version Control', 'DevOps'],
    educationLevels: ['intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Computer Science & Software',
    difficulty: 'Beginner',
    duration: '1 hour 8 mins',
    tags: ['git', 'github', 'version control']
  },
  {
    resourceId: 'HXV3zeQKqGY',
    title: 'SQL Tutorial — Full Database Course for Beginners',
    description: 'Master relational database management systems (RDBMS), SQL queries, tables, CRUD operations, joins, aggregations, and nested queries.',
    url: 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
    provider: 'freeCodeCamp',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/HXV3zeQKqGY/maxresdefault.jpg',
    channel: 'freeCodeCamp.org',
    careerIds: ['software_engineer', 'data_scientist', 'financial_analyst', 'business_owner'],
    skills: ['SQL', 'Databases', 'Data Analysis'],
    educationLevels: ['intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Computer Science & Software',
    difficulty: 'Beginner',
    duration: '4 hours 20 mins',
    tags: ['sql', 'database', 'mysql', 'queries']
  },
  {
    resourceId: 'grEKMHGYyns',
    title: 'Java Tutorial for Beginners [Full Course]',
    description: 'Object-Oriented Programming (OOP) in Java: Classes, Encapsulation, Inheritance, Polymorphism, Exception Handling, Collections Framework, and JVM fundamentals.',
    url: 'https://www.youtube.com/watch?v=grEKMHGYyns',
    provider: 'Programming with Mosh',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/grEKMHGYyns/maxresdefault.jpg',
    channel: 'Programming with Mosh',
    careerIds: ['software_engineer'],
    skills: ['Java', 'Programming', 'OOP'],
    educationLevels: ['intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Computer Science & Software',
    difficulty: 'Beginner',
    duration: '2 hours 30 mins',
    tags: ['java', 'oop', 'software']
  },

  // ─── 2. ARTIFICIAL INTELLIGENCE & DATA SCIENCE ──────────────────────────────
  {
    resourceId: 'i_LwzRVP7bg',
    title: 'Machine Learning for Everybody — Full Course',
    description: 'Fundamental ML concepts: Supervised learning, Unsupervised learning, Linear Regression, Logistic Regression, KNN, Decision Trees, Random Forests, and Neural Networks.',
    url: 'https://www.youtube.com/watch?v=i_LwzRVP7bg',
    provider: 'freeCodeCamp',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/i_LwzRVP7bg/maxresdefault.jpg',
    channel: 'freeCodeCamp.org',
    careerIds: ['ai_engineer', 'ml_engineer', 'data_scientist'],
    skills: ['Machine Learning', 'Artificial Intelligence', 'Python', 'Statistical Analysis'],
    educationLevels: ['undergraduate', 'postgraduate'],
    topicCategory: 'Data & Artificial Intelligence',
    difficulty: 'Intermediate',
    duration: '3 hours 53 mins',
    tags: ['machine learning', 'ml', 'ai', 'data science']
  },
  {
    resourceId: 'r-uOLxNrNk8',
    title: 'Data Analysis with Python Course — Numpy, Pandas, Matplotlib, Seaborn',
    description: 'Learn Data Wrangling, statistical exploration, Pandas DataFrame transformations, NumPy vector math, and Matplotlib data visualization.',
    url: 'https://www.youtube.com/watch?v=r-uOLxNrNk8',
    provider: 'freeCodeCamp',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/r-uOLxNrNk8/maxresdefault.jpg',
    channel: 'freeCodeCamp.org',
    careerIds: ['data_scientist', 'financial_analyst', 'ai_engineer'],
    skills: ['Data Science', 'Python', 'Data Analysis', 'Statistical Analysis'],
    educationLevels: ['intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Data & Artificial Intelligence',
    difficulty: 'Beginner',
    duration: '4 hours 24 mins',
    tags: ['data analysis', 'pandas', 'numpy', 'python']
  },
  {
    resourceId: 'aircAruvnKk',
    title: 'Neural Networks and Deep Learning — MIT Introduction',
    description: 'Core Deep Learning mathematics, Perceptrons, Backpropagation, Gradient Descent, Convolutional Neural Networks (CNNs), and Transformers.',
    url: 'https://www.youtube.com/watch?v=aircAruvnKk',
    provider: '3Blue1Brown',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/aircAruvnKk/maxresdefault.jpg',
    channel: '3Blue1Brown',
    careerIds: ['ai_engineer', 'ml_engineer'],
    skills: ['Artificial Intelligence', 'Deep Learning', 'Machine Learning'],
    educationLevels: ['undergraduate', 'postgraduate'],
    topicCategory: 'Data & Artificial Intelligence',
    difficulty: 'Advanced',
    duration: '1 hour 45 mins',
    tags: ['deep learning', 'neural networks', 'ai']
  },

  // ─── 3. CYBERSECURITY & NETWORKING ──────────────────────────────────────────
  {
    resourceId: '3Kq1MIfTWCE',
    title: 'Cybersecurity for Beginners — Full Course',
    description: 'Network protocols (TCP/IP, DNS, HTTPS), Firewalls, Threat Vectors, Cryptography, Identity & Access Management (IAM), and Penetration Testing fundamentals.',
    url: 'https://www.youtube.com/watch?v=3Kq1MIfTWCE',
    provider: 'freeCodeCamp',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/3Kq1MIfTWCE/maxresdefault.jpg',
    channel: 'freeCodeCamp.org',
    careerIds: ['cybersecurity_analyst', 'cloud_engineer'],
    skills: ['Cybersecurity', 'Networking', 'Cloud'],
    educationLevels: ['intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Cybersecurity & Infrastructure',
    difficulty: 'Beginner',
    duration: '2 hours 15 mins',
    tags: ['cybersecurity', 'security', 'networking', 'hacking']
  },

  // ─── 4. MEDICINE & HEALTHCARE ───────────────────────────────────────────────
  {
    resourceId: 'uBGl2BujkPQ',
    title: 'Introduction to Human Anatomy and Physiology',
    description: 'Overview of human organ systems: Circulatory, Respiratory, Nervous, Musculoskeletal, Endocrine, and Digestive mechanisms.',
    url: 'https://www.youtube.com/watch?v=uBGl2BujkPQ',
    provider: 'CrashCourse',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/uBGl2BujkPQ/maxresdefault.jpg',
    channel: 'CrashCourse Anatomy & Physiology',
    careerIds: ['doctor', 'surgeon', 'nurse', 'dentist', 'pharmacist'],
    skills: ['Clinical Diagnosis', 'Patient Care', 'Medicine', 'Biology'],
    educationLevels: ['school', 'intermediate', 'undergraduate'],
    topicCategory: 'Medical & Healthcare',
    difficulty: 'Beginner',
    duration: '11 mins',
    tags: ['anatomy', 'physiology', 'medicine', 'doctor', 'neet']
  },
  {
    resourceId: 'f_J8QU1m0_E',
    title: 'Clinical Examination & Patient History Taking Essentials',
    description: 'Clinical examination steps: Vital signs (BP, Pulse, Respiration), physical inspection, auscultation, differential diagnosis, and patient communication.',
    url: 'https://www.youtube.com/watch?v=f_J8QU1m0_E',
    provider: 'Geeky Medics',
    type: 'Interactive Lab',
    thumbnail: 'https://img.youtube.com/vi/f_J8QU1m0_E/maxresdefault.jpg',
    channel: 'Geeky Medics Clinical OSCE',
    careerIds: ['doctor', 'nurse', 'surgeon'],
    skills: ['Clinical Diagnosis', 'Patient Care', 'Medical Ethics'],
    educationLevels: ['undergraduate'],
    topicCategory: 'Medical & Healthcare',
    difficulty: 'Intermediate',
    duration: '18 mins',
    tags: ['clinical diagnosis', 'mbbs', 'osce', 'medicine']
  },
  {
    resourceId: 'Oq51fA6zE_E',
    title: 'Pharmacology Fundamentals — Drug Classes & Pharmacokinetics',
    description: 'Pharmacokinetics (Absorption, Distribution, Metabolism, Excretion), Pharmacodynamics, receptor binding, and primary drug interaction mechanisms.',
    url: 'https://www.youtube.com/watch?v=Oq51fA6zE_E',
    provider: 'Speed Pharmacology',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/Oq51fA6zE_E/maxresdefault.jpg',
    channel: 'Speed Pharmacology',
    careerIds: ['pharmacist', 'doctor'],
    skills: ['Pharmacology', 'Drug Formulation', 'Medicine'],
    educationLevels: ['intermediate', 'undergraduate'],
    topicCategory: 'Medical & Healthcare',
    difficulty: 'Intermediate',
    duration: '13 mins',
    tags: ['pharmacology', 'drugs', 'bpharm', 'pharmacy']
  },

  // ─── 5. COMMERCE, ACCOUNTING & FINANCE ──────────────────────────────────────
  {
    resourceId: 'yYX4bvQSqbo',
    title: 'Accounting Basics Explained Through a Story',
    description: 'Accounting equation (Assets = Liabilities + Equity), double-entry bookkeeping, debit and credit rules, journal entries, ledger accounts, and balance sheet preparation.',
    url: 'https://www.youtube.com/watch?v=yYX4bvQSqbo',
    provider: 'Accounting Stuff',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/yYX4bvQSqbo/maxresdefault.jpg',
    channel: 'Accounting Stuff',
    careerIds: ['chartered_accountant', 'financial_analyst', 'investment_banker', 'business_owner'],
    skills: ['Accounting', 'Financial Accounting', 'Finance'],
    educationLevels: ['school', 'intermediate', 'undergraduate'],
    topicCategory: 'Commerce & Finance',
    difficulty: 'Beginner',
    duration: '9 mins',
    tags: ['accounting', 'commerce', 'ca foundation', 'bookkeeping']
  },
  {
    resourceId: 'V9DlhfZsm_g',
    title: 'Financial Modeling & Valuation Fundamentals in Excel',
    description: 'Building 3-statement financial models (P&L, Balance Sheet, Cash Flow), Discounted Cash Flow (DCF) valuation, and sensitivity analysis for corporate finance.',
    url: 'https://www.youtube.com/watch?v=V9DlhfZsm_g',
    provider: 'Corporate Finance Institute',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/V9DlhfZsm_g/maxresdefault.jpg',
    channel: 'Corporate Finance Institute (CFI)',
    careerIds: ['financial_analyst', 'investment_banker', 'chartered_accountant'],
    skills: ['Finance', 'Excel', 'Financial Modeling', 'Valuation & M&A'],
    educationLevels: ['undergraduate', 'postgraduate'],
    topicCategory: 'Commerce & Finance',
    difficulty: 'Intermediate',
    duration: '45 mins',
    tags: ['financial modeling', 'finance', 'excel', 'valuation']
  },
  {
    resourceId: 'g7zS9e2Z3kY',
    title: 'Tally Prime Full Course — GST, Invoicing & Inventory Management',
    description: 'Hands-on Tally Prime walkthrough: Company creation, vouchers, GST calculation, e-way billing, inventory tracking, and financial statement generation.',
    url: 'https://www.youtube.com/watch?v=g7zS9e2Z3kY',
    provider: 'Career Planet Computer Education',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/g7zS9e2Z3kY/maxresdefault.jpg',
    channel: 'Career Planet',
    careerIds: ['chartered_accountant', 'business_owner'],
    skills: ['Tally', 'Accounting', 'Taxation & Auditing'],
    educationLevels: ['intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Commerce & Finance',
    difficulty: 'Beginner',
    duration: '2 hours 15 mins',
    tags: ['tally', 'gst', 'accounting', 'tax']
  },

  // ─── 6. LAW & GOVERNANCE ────────────────────────────────────────────────────
  {
    resourceId: 'mNNhdx4jFGs',
    title: 'Indian Constitution & Constitutional Law — Master Lecture Series',
    description: 'Preamble, Fundamental Rights (Articles 12-35), Directive Principles of State Policy (DPSP), Judiciary structure, Judicial Review, and landmark Supreme Court cases.',
    url: 'https://www.youtube.com/watch?v=mNNhdx4jFGs',
    provider: 'StudyIQ IAS',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/mNNhdx4jFGs/maxresdefault.jpg',
    channel: 'StudyIQ IAS',
    careerIds: ['lawyer', 'judge', 'ias_officer', 'ips_officer'],
    skills: ['Law', 'Constitutional Law', 'Civil Services', 'Public Administration'],
    educationLevels: ['intermediate', 'undergraduate'],
    topicCategory: 'Law & Governance',
    difficulty: 'Intermediate',
    duration: '1 hour 30 mins',
    tags: ['constitution', 'law', 'clat', 'upsc', 'judiciary']
  },
  {
    resourceId: 'd6yZ6aE1g3g',
    title: 'Legal Drafting & Courtroom Advocacy Masterclass',
    description: 'Drafting legal notices, writ petitions, civil suits, criminal complaints, contract negotiation clauses, and statutory interpretations.',
    url: 'https://www.youtube.com/watch?v=d6yZ6aE1g3g',
    provider: 'Lawctopus',
    type: 'Video Masterclass',
    thumbnail: 'https://img.youtube.com/vi/d6yZ6aE1g3g/maxresdefault.jpg',
    channel: 'Lawctopus Law School',
    careerIds: ['lawyer', 'judge'],
    skills: ['Legal Drafting', 'Law', 'Negotiation', 'Public Speaking'],
    educationLevels: ['undergraduate'],
    topicCategory: 'Law & Governance',
    difficulty: 'Intermediate',
    duration: '52 mins',
    tags: ['legal drafting', 'advocacy', 'law', 'clat']
  },

  // ─── 7. CORE ENGINEERING & DESIGN ───────────────────────────────────────────
  {
    resourceId: 'cmR9cfWJRUU',
    title: 'AutoCAD Basic Tutorial for Beginners — 2D Drawing & Architecture',
    description: 'AutoCAD user interface, coordinate system, line commands, dimensioning, layers, blocks, and architectural floor plan drafting.',
    url: 'https://www.youtube.com/watch?v=cmR9cfWJRUU',
    provider: 'CAD in Black',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/cmR9cfWJRUU/maxresdefault.jpg',
    channel: 'CAD in Black',
    careerIds: ['civil_engineer', 'architect', 'mechanical_engineer'],
    skills: ['CAD', 'AutoCAD', 'Civil Engineering', '3D Modeling'],
    educationLevels: ['diploma', 'undergraduate'],
    topicCategory: 'Core Engineering & Design',
    difficulty: 'Beginner',
    duration: '2 hours 10 mins',
    tags: ['autocad', 'cad', 'civil', 'architecture', 'engineering']
  },
  {
    resourceId: 'qzgS9n_Q7vM',
    title: 'SolidWorks 3D Modeling Tutorial for Mechanical Engineers',
    description: 'Parametric 3D solid modeling: Sketching, extrusions, revolves, sweeps, fillets, assembly mating, and drafting sheets for mechanical production.',
    url: 'https://www.youtube.com/watch?v=qzgS9n_Q7vM',
    provider: 'SolidWorks Tutorial CAD',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/qzgS9n_Q7vM/maxresdefault.jpg',
    channel: 'CAD CAM TUTORIAL',
    careerIds: ['mechanical_engineer', 'robotics_engineer'],
    skills: ['SolidWorks', 'CAD', 'Mechanical Repair'],
    educationLevels: ['diploma', 'undergraduate'],
    topicCategory: 'Core Engineering & Design',
    difficulty: 'Beginner',
    duration: '1 hour 40 mins',
    tags: ['solidworks', 'mechanical', 'cad', '3d modeling']
  },
  {
    resourceId: 'FTFaQWZBqQ8',
    title: 'Figma UI/UX Design Tutorial — From Beginner to Pro',
    description: 'Learn wireframing, component design systems, auto-layout, typography hierarchies, interactive prototyping, and design handoff workflows in Figma.',
    url: 'https://www.youtube.com/watch?v=FTFaQWZBqQ8',
    provider: 'DesignCourse',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/FTFaQWZBqQ8/maxresdefault.jpg',
    channel: 'DesignCourse',
    careerIds: ['ui_designer', 'ux_designer', 'product_manager'],
    skills: ['Figma', 'UI/UX', 'Creativity', 'Prototyping', 'Design Systems'],
    educationLevels: ['school', 'intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Design & Visual Arts',
    difficulty: 'Beginner',
    duration: '3 hours 12 mins',
    tags: ['figma', 'ui/ux', 'design', 'prototyping']
  },
  {
    resourceId: 'nIoXOplUvAw',
    title: 'Blender 3D Modeling & Animation — Complete Beginner Guide',
    description: 'Getting started in Blender: Viewport navigation, mesh editing, modifiers, lighting, texturing, rigging, and keyframe animation fundamentals.',
    url: 'https://www.youtube.com/watch?v=nIoXOplUvAw',
    provider: 'Blender Guru',
    type: 'Full Course',
    thumbnail: 'https://img.youtube.com/vi/nIoXOplUvAw/maxresdefault.jpg',
    channel: 'Blender Guru',
    careerIds: ['animator', 'game_developer', 'interior_designer'],
    skills: ['Blender', 'Animation', 'Creativity', 'Motion Graphics'],
    educationLevels: ['school', 'intermediate', 'diploma', 'undergraduate'],
    topicCategory: 'Design & Visual Arts',
    difficulty: 'Beginner',
    duration: '4 hours 15 mins',
    tags: ['blender', '3d animation', 'cgi', 'vfx']
  }
];
