import config from '../config/env';
import { CareerRoadmap, ICareerRoadmapDocument, IMilestone, IRoadmapStage } from '../models/CareerRoadmap';
import { CareerProgress } from '../models/CareerProgress';
import { CareerAssessment, IQuestion, SkillDifficulty } from '../models/CareerAssessment';
import { UserProfile } from '../models/UserProfile';
import { PersonalizationService } from './personalization.service';
import { MatchService } from './match.service';
import { CAREERS_DATA } from '../constants/careers.constants';
import mongoose from 'mongoose';

export class RoadmapService {
  /**
   * Generates a personalized roadmap for a user's target career.
   * If Gemini is configured and accessible, it uses AI. Otherwise, it falls back to a detailed deterministic builder.
   */
  public static async generateRoadmap(userId: string, careerId: string): Promise<ICareerRoadmapDocument> {
    // 1. Fetch personalization context
    const pContext = await PersonalizationService.getPersonalizationContext(userId);
    
    // 2. Fetch career details
    const career = CAREERS_DATA.find((c) => c.id === careerId);
    if (!career) {
      throw new Error(`Career not found: ${careerId}`);
    }

    // 3. Calculate Phase 9 Career Match details
    const match = MatchService.calculateMatch(career, pContext);

    // 4. Try AI generation if API key exists
    let stages: IRoadmapStage[] = [];
    let generatedBy: 'ai' | 'fallback' = 'fallback';

    if (config.GEMINI_API_KEY && config.GEMINI_API_KEY.trim().length > 0) {
      try {
        stages = await this.generateRoadmapWithAi(pContext, career, match);
        generatedBy = 'ai';
        console.log(`[RoadmapService] Roadmap for ${career.title} successfully generated by Gemini AI.`);
      } catch (err: any) {
        console.warn(`[RoadmapService] Gemini AI roadmap generation failed, falling back to deterministic:`, err?.message || err);
      }
    }

    // 5. Fallback to deterministic if AI generation failed or wasn't run
    if (stages.length === 0) {
      stages = this.generateDeterministicRoadmap(pContext, career, match);
      generatedBy = 'fallback';
    }

    // 6. Save or update the roadmap in the database
    // Using findOneAndUpdate with upsert ensures we can overwrite if requested, or create new.
    const roadmap = await CareerRoadmap.findOneAndUpdate(
      { userId: new mongoose.Types.ObjectId(userId), careerId },
      {
        userId: new mongoose.Types.ObjectId(userId),
        careerId,
        careerTitle: career.title,
        stages,
        progress: 0, // Freshly generated roadmaps start at 0%
      },
      { upsert: true, new: true }
    );

    // 7. Update active career details in CareerProgress model to match the active selected career
    await CareerProgress.findOneAndUpdate(
      { userId: new mongoose.Types.ObjectId(userId) },
      {
        selectedCareer: career.title,
        currentPhase: 1, // Start Phase 10
        completedMilestones: [],
        totalMilestones: this.countMilestones(stages),
        lastActivity: new Date(),
      },
      { upsert: true }
    );

    return roadmap;
  }

  /**
   * Fetches the user's active roadmap.
   * Sanitizes milestone statuses on the fly for backwards compatibility with legacy profiles.
   */
  public static async getRoadmap(userId: string, careerId?: string): Promise<ICareerRoadmapDocument | null> {
    const query: any = { userId: new mongoose.Types.ObjectId(userId) };
    if (careerId) {
      query.careerId = careerId;
    }
    
    // If careerId is not specified, check the user's active career in CareerProgress first
    let targetCareerId = careerId;
    if (!targetCareerId) {
      const progress = await CareerProgress.findOne({ userId: new mongoose.Types.ObjectId(userId) });
      const selCareer = progress?.selectedCareer;
      if (selCareer) {
        // Map the title back to an ID
        const matchedCareer = CAREERS_DATA.find(
          c => c.title.toLowerCase() === selCareer.toLowerCase() || c.id.toLowerCase() === selCareer.toLowerCase()
        );
        if (matchedCareer) {
          targetCareerId = matchedCareer.id;
        }
      }
    }

    // If still not found, check UserProfile dreamCareer
    if (!targetCareerId) {
      const profile = await UserProfile.findOne({ userId: new mongoose.Types.ObjectId(userId) });
      const dreamCareer = profile?.careerGoals?.dreamCareer;
      if (dreamCareer) {
        const matchedCareer = CAREERS_DATA.find(
          c => c.title.toLowerCase() === dreamCareer.toLowerCase() || c.id.toLowerCase() === dreamCareer.toLowerCase()
        );
        if (matchedCareer) {
          targetCareerId = matchedCareer.id;
        }
      }
    }

    let roadmap: ICareerRoadmapDocument | null = null;
    if (!targetCareerId) {
      // Fallback: Return the most recently updated roadmap if any exists
      roadmap = await CareerRoadmap.findOne({ userId: new mongoose.Types.ObjectId(userId) }).sort({ updatedAt: -1 });
    } else {
      roadmap = await CareerRoadmap.findOne({ userId: new mongoose.Types.ObjectId(userId), careerId: targetCareerId });
      // If user has a valid targetCareerId but no roadmap document exists yet, auto-generate initial roadmap!
      if (!roadmap) {
        try {
          roadmap = await this.generateRoadmap(userId, targetCareerId);
        } catch (genErr: any) {
          console.warn('[RoadmapService] Could not auto-generate initial roadmap for target career:', genErr?.message || genErr);
        }
      }
    }

    // Apply on-the-fly status sanitization for backward compatibility
    if (roadmap) {
      let changed = false;
      roadmap.stages.forEach((stage) => {
        stage.milestones.forEach((milestone) => {
          if (!milestone.status) {
            milestone.status = milestone.completed ? 'Completed & Verified' : 'Upcoming';
            changed = true;
          }
          if (milestone.assessmentAttempted === undefined) {
            milestone.assessmentAttempted = false;
            changed = true;
          }
          if (milestone.assessmentScore === undefined) {
            milestone.assessmentScore = 0;
            changed = true;
          }
          if (milestone.assessmentStatus === undefined) {
            milestone.assessmentStatus = null;
            changed = true;
          }
          if (milestone.assessmentAttemptedAt === undefined) {
            milestone.assessmentAttemptedAt = null;
            changed = true;
          }
          if (milestone.retakeAvailable === undefined) {
            milestone.retakeAvailable = true;
            changed = true;
          }
        });
      });

      if (changed) {
        await roadmap.save();
      }
    }

    return roadmap;
  }

  /**
   * Transition a milestone's status from 'Upcoming' to 'In Progress'.
   */
  public static async startMilestone(
    userId: string,
    careerId: string,
    milestoneId: string
  ): Promise<ICareerRoadmapDocument> {
    const userObjectId = new mongoose.Types.ObjectId(userId);
    const roadmap = await CareerRoadmap.findOne({ userId: userObjectId, careerId });
    if (!roadmap) {
      throw new Error(`Roadmap not found for career: ${careerId}`);
    }

    let milestoneFound = false;
    for (const stage of roadmap.stages) {
      const milestone = stage.milestones.find((m) => m.id === milestoneId);
      if (milestone) {
        if (milestone.status === 'Upcoming') {
          milestone.status = 'In Progress';
        }
        milestoneFound = true;
        break;
      }
    }

    if (!milestoneFound) {
      throw new Error(`Milestone ${milestoneId} not found in roadmap.`);
    }

    await roadmap.save();
    return roadmap;
  }

  /**
   * Generates or retrieves an existing uncompleted milestone assessment.
   * Strips correct answers to prevent client-side scoring manipulation.
   */
  public static async generateMilestoneAssessment(
    userId: string,
    careerId: string,
    milestoneId: string
  ): Promise<any[]> {
    const userObjectId = new mongoose.Types.ObjectId(userId);

    // Check if there is an existing uncompleted assessment for this milestone with valid questions
    let assessment = await CareerAssessment.findOne({
      userId: userObjectId,
      careerId,
      milestoneId,
      completed: false,
    });

    if (assessment && (!assessment.questions || assessment.questions.length === 0)) {
      // Remove corrupt/empty uncompleted attempt
      await CareerAssessment.deleteOne({ _id: assessment._id });
      assessment = null;
    }

    if (!assessment) {
      // Fetch roadmap and milestone details to customize the questions
      const roadmap = await CareerRoadmap.findOne({ userId: userObjectId, careerId });
      if (!roadmap) throw new Error(`Roadmap not found for career: ${careerId}`);

      let milestone: IMilestone | null = null;
      for (const stage of roadmap.stages) {
        const found = stage.milestones.find((m) => m.id === milestoneId);
        if (found) {
          milestone = found;
          break;
        }
      }
      if (!milestone) throw new Error(`Milestone not found: ${milestoneId}`);

      if (!config.GEMINI_API_KEY || config.GEMINI_API_KEY.trim().length === 0) {
        throw new Error('AI assessment generation is currently unavailable (GEMINI_API_KEY not configured).');
      }

      const questions = await this.generateAssessmentQuestionsWithAi(milestone, roadmap.careerTitle);

      if (!questions || questions.length === 0) {
        throw new Error('Could not generate assessment questions for this milestone. Please try again.');
      }

      assessment = new CareerAssessment({
        userId: userObjectId,
        careerId,
        milestoneId,
        questions,
        completed: false,
      });
      await assessment.save();
    }

    // Strip out correctAnswerIndex before sending to the client
    return assessment.questions.map((q) => ({
      question: q.question,
      options: q.options,
    }));
  }

  /**
   * Generates or retrieves an uncompleted standalone skill assessment.
   */
  public static async generateStandaloneSkillAssessment(
    userId: string,
    skillName: string,
    domain?: string,
    difficulty: SkillDifficulty = 'Intermediate'
  ): Promise<{ assessmentId: string; skillName: string; difficulty: string; domain: string; questions: Array<{ question: string; options: string[] }> }> {
    const userObjectId = new mongoose.Types.ObjectId(userId);
    const cleanSkillName = skillName.trim();
    if (!cleanSkillName) {
      throw new Error('Skill name is required.');
    }

    // Check if there is an existing uncompleted assessment for this skill
    let assessment = await CareerAssessment.findOne({
      userId: userObjectId,
      assessmentType: 'standalone_skill',
      skillName: cleanSkillName,
      completed: false,
    });

    if (assessment && (!assessment.questions || assessment.questions.length === 0)) {
      await CareerAssessment.deleteOne({ _id: assessment._id });
      assessment = null;
    }

    if (!assessment) {
      if (!config.GEMINI_API_KEY || config.GEMINI_API_KEY.trim().length === 0) {
        throw new Error('AI assessment generation is currently unavailable (GEMINI_API_KEY not configured).');
      }

      // Fetch user profile for discipline context if available
      const profile = await UserProfile.findOne({ userId: userObjectId });
      const userDiscipline = profile?.education?.stream || domain || 'General';

      const questions = await this.generateSkillQuestionsWithAi(cleanSkillName, domain || userDiscipline, difficulty);

      if (!questions || questions.length === 0) {
        throw new Error(`Could not generate assessment questions for skill: ${cleanSkillName}. Please try again.`);
      }

      assessment = new CareerAssessment({
        userId: userObjectId,
        assessmentType: 'standalone_skill',
        skillName: cleanSkillName,
        domain: domain || userDiscipline,
        difficulty,
        questions,
        completed: false,
      });
      await assessment.save();
    }

    return {
      assessmentId: (assessment._id as mongoose.Types.ObjectId).toString(),
      skillName: assessment.skillName || cleanSkillName,
      difficulty: assessment.difficulty || difficulty,
      domain: assessment.domain || domain || 'General',
      questions: assessment.questions.map((q) => ({
        question: q.question,
        options: q.options,
      })),
    };
  }

  /**
   * Evaluates answers for a standalone skill assessment and updates UserProfile.skills.verifiedSkills on pass.
   */
  public static async submitStandaloneSkillAssessment(
    userId: string,
    assessmentId: string,
    answers: number[]
  ): Promise<{ assessmentId: string; skillName: string; score: number; passed: boolean; difficulty?: string }> {
    const userObjectId = new mongoose.Types.ObjectId(userId);
    const assessment = await CareerAssessment.findOne({
      _id: new mongoose.Types.ObjectId(assessmentId),
      userId: userObjectId,
      completed: false,
    });

    if (!assessment) {
      throw new Error('Active skill assessment not found or already completed.');
    }

    if (!assessment.questions || assessment.questions.length === 0) {
      throw new Error('Assessment questions are missing.');
    }

    const totalQuestions = assessment.questions.length;
    let correctCount = 0;
    assessment.questions.forEach((q, idx) => {
      if (answers[idx] === q.correctAnswerIndex) {
        correctCount += 1;
      }
    });

    const score = Math.round((correctCount / totalQuestions) * 100);
    const passed = score >= 60;

    assessment.score = score;
    assessment.passed = passed;
    assessment.completed = true;
    await assessment.save();

    const skillName = assessment.skillName || 'Skill';

    // If passed, record into UserProfile.skills.verifiedSkills without duplicates
    if (passed) {
      try {
        const profile = await UserProfile.findOne({ userId: userObjectId });
        if (profile) {
          if (!profile.skills) {
            profile.skills = { technicalSkills: [], softSkills: [], languages: [], skillLevels: new Map(), verifiedSkills: [] };
          }
          if (!profile.skills.verifiedSkills) {
            profile.skills.verifiedSkills = [];
          }

          const cleanSkill = skillName.trim();
          const existingIdx = profile.skills.verifiedSkills.findIndex(
            (vs) => vs.name.toLowerCase() === cleanSkill.toLowerCase()
          );

          const now = new Date();
          if (existingIdx === -1) {
            profile.skills.verifiedSkills.push({
              name: cleanSkill,
              verifiedAt: now,
              source: 'skill_assessment',
              assessmentId: assessment._id.toString(),
              score,
            });
          } else {
            // Update timestamp and score if higher
            profile.skills.verifiedSkills[existingIdx].verifiedAt = now;
            profile.skills.verifiedSkills[existingIdx].assessmentId = assessment._id.toString();
            if (score > (profile.skills.verifiedSkills[existingIdx].score || 0)) {
              profile.skills.verifiedSkills[existingIdx].score = score;
            }
          }
          await profile.save();
        }
      } catch (profileErr) {
        console.error('Error updating verified skill on profile:', profileErr);
      }
    }

    return {
      assessmentId: assessment._id.toString(),
      skillName,
      score,
      passed,
      difficulty: assessment.difficulty,
    };
  }

  /**
   * Resets uncompleted attempts for a standalone skill to allow retaking fresh.
   */
  public static async resetStandaloneSkillAssessment(userId: string, skillName: string): Promise<void> {
    const userObjectId = new mongoose.Types.ObjectId(userId);
    const cleanSkillName = skillName.trim();
    await CareerAssessment.deleteMany({
      userId: userObjectId,
      assessmentType: 'standalone_skill',
      skillName: cleanSkillName,
      completed: false,
    });
  }

  /**
   * Scores the user's answers against the correct index on the server side.
   * Updates milestone status and recalculates overall progress.
   */
  public static async submitMilestoneAssessment(
    userId: string,
    careerId: string,
    milestoneId: string,
    answers: number[]
  ): Promise<{ score: number; passed: boolean; roadmap: ICareerRoadmapDocument }> {
    const userObjectId = new mongoose.Types.ObjectId(userId);

    // Fetch the active, uncompleted assessment attempt
    const assessment = await CareerAssessment.findOne({
      userId: userObjectId,
      careerId,
      milestoneId,
      completed: false,
    });

    if (!assessment) {
      throw new Error('No active assessment attempt found for this milestone.');
    }

    const totalQuestions = assessment.questions.length;
    if (answers.length !== totalQuestions) {
      throw new Error(`Incomplete submission. Expected ${totalQuestions} answers, received ${answers.length}.`);
    }

    // Calculate score
    let correctCount = 0;
    assessment.questions.forEach((q, idx) => {
      if (answers[idx] === q.correctAnswerIndex) {
        correctCount++;
      }
    });

    const score = Math.round((correctCount / totalQuestions) * 100);
    const passed = score >= 60; // 60% passing threshold

    // Save assessment results
    assessment.completed = true;
    assessment.score = score;
    assessment.passed = passed;
    await assessment.save();

    // Fetch roadmap to update milestone status
    const roadmap = await CareerRoadmap.findOne({ userId: userObjectId, careerId });
    if (!roadmap) {
      throw new Error('Roadmap not found.');
    }

    let milestoneFound = false;
    for (const stage of roadmap.stages) {
      const milestone = stage.milestones.find((m) => m.id === milestoneId);
      if (milestone) {
        milestone.completed = true; // Both statuses count as completed!
        milestone.status = passed ? 'Completed & Verified' : 'Completed — Review Recommended';
        milestone.assessmentAttempted = true;
        milestone.assessmentScore = score;
        milestone.assessmentStatus = passed ? 'passed' : 'failed';
        milestone.assessmentAttemptedAt = new Date();
        milestone.retakeAvailable = !passed; // Retake is available only if they failed to verify
        milestoneFound = true;

        // If passed, record milestone skills into UserProfile verifiedSkills
        if (passed && milestone.skills && milestone.skills.length > 0) {
          try {
            const profile = await UserProfile.findOne({ userId: userObjectId });
            if (profile) {
              if (!profile.skills) {
                profile.skills = {
                  technicalSkills: [],
                  softSkills: [],
                  languages: [],
                  certifications: [],
                  portfolioLinks: {},
                  skillLevels: new Map(),
                  verifiedSkills: [],
                };
              }
              if (!profile.skills.verifiedSkills) {
                profile.skills.verifiedSkills = [];
              }

              const existingVerifiedMap = new Set<string>();
              profile.skills.verifiedSkills.forEach((vs) => {
                if (vs && vs.name) {
                  existingVerifiedMap.add(vs.name.trim().toLowerCase());
                }
              });

              const now = new Date();
              const assessmentId = (assessment._id as mongoose.Types.ObjectId).toString();

              for (const skillName of milestone.skills) {
                const cleanSkill = skillName.trim();
                if (cleanSkill && !existingVerifiedMap.has(cleanSkill.toLowerCase())) {
                  profile.skills.verifiedSkills.push({
                    name: cleanSkill,
                    verifiedAt: now,
                    source: 'milestone_assessment',
                    assessmentId,
                    careerId,
                    milestoneId,
                    score,
                  });
                  existingVerifiedMap.add(cleanSkill.toLowerCase());
                }
              }
              await profile.save();
            }
          } catch (profileErr) {
            console.error('Error updating verified skills on profile:', profileErr);
          }
        }

        break;
      }
    }

    if (!milestoneFound) {
      throw new Error('Milestone not found in roadmap during grading.');
    }

    // Recalculate progress: count both 'Completed & Verified' and 'Completed — Review Recommended' as completed
    const allMilestones: IMilestone[] = [];
    roadmap.stages.forEach((stage) => {
      stage.milestones.forEach((m) => allMilestones.push(m));
    });

    const totalCount = allMilestones.length;
    const completedCount = allMilestones.filter(
      (m) => m.completed || m.status === 'Completed & Verified' || m.status === 'Completed — Review Recommended'
    ).length;
    const progressPercent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

    roadmap.progress = progressPercent;
    await roadmap.save();

    // Sync with CareerProgress model
    const completedIds = allMilestones
      .filter((m) => m.completed || m.status === 'Completed & Verified' || m.status === 'Completed — Review Recommended')
      .map((m) => m.id);

    await CareerProgress.findOneAndUpdate(
      { userId: userObjectId },
      {
        selectedCareer: roadmap.careerTitle,
        completedMilestones: completedIds,
        totalMilestones: totalCount,
        lastActivity: new Date(),
      },
      { upsert: true }
    );

    return {
      score,
      passed,
      roadmap,
    };
  }

  /**
   * Delete failed assessment attempts to allow retaking.
   */
  public static async resetMilestoneAssessment(
    userId: string,
    careerId: string,
    milestoneId: string
  ): Promise<void> {
    const userObjectId = new mongoose.Types.ObjectId(userId);
    // Delete any uncompleted/completed attempts to refresh questions on retake
    await CareerAssessment.deleteMany({
      userId: userObjectId,
      careerId,
      milestoneId,
    });

    // Remove verified skills associated with this specific milestone assessment
    try {
      const profile = await UserProfile.findOne({ userId: userObjectId });
      if (profile && profile.skills && profile.skills.verifiedSkills) {
        profile.skills.verifiedSkills = profile.skills.verifiedSkills.filter(
          (vs) => !(vs.careerId === careerId && vs.milestoneId === milestoneId)
        );
        await profile.save();
      }
    } catch (err) {
      console.warn('Error removing reset verified skills from profile:', err);
    }
  }

  /**
   * Toggle completion status of a milestone.
   * Ensures status is updated correctly and progress counts both completed states.
   */
  public static async toggleMilestone(
    userId: string,
    careerId: string,
    milestoneId: string,
    completed: boolean
  ): Promise<ICareerRoadmapDocument> {
    const userObjectId = new mongoose.Types.ObjectId(userId);
    const roadmap = await CareerRoadmap.findOne({ userId: userObjectId, careerId });
    if (!roadmap) {
      throw new Error(`No roadmap found for career: ${careerId}`);
    }

    // Toggle completed status on the specific milestone
    let milestoneFound = false;
    for (const stage of roadmap.stages) {
      const milestone = stage.milestones.find((m) => m.id === milestoneId);
      if (milestone) {
        milestone.completed = completed;
        if (completed) {
          // If already verified through a passed assessment, keep verified status, otherwise mark as Review Recommended
          milestone.status = milestone.assessmentStatus === 'passed' ? 'Completed & Verified' : 'Completed — Review Recommended';
        } else {
          milestone.status = 'Upcoming';
          // Reset quiz telemetry if toggled off
          milestone.assessmentAttempted = false;
          milestone.assessmentScore = 0;
          milestone.assessmentStatus = null;
          milestone.assessmentAttemptedAt = null;
          milestone.retakeAvailable = true;
          // Delete assessments and remove associated verified skills
          await this.resetMilestoneAssessment(userId, careerId, milestoneId);
        }
        milestoneFound = true;
        break;
      }
    }

    if (!milestoneFound) {
      throw new Error(`Milestone ${milestoneId} not found in roadmap.`);
    }

    // Recalculate progress percentage
    const allMilestones: IMilestone[] = [];
    roadmap.stages.forEach((stage) => {
      stage.milestones.forEach((m) => allMilestones.push(m));
    });

    const totalCount = allMilestones.length;
    const completedCount = allMilestones.filter(
      (m) => m.completed || m.status === 'Completed & Verified' || m.status === 'Completed — Review Recommended'
    ).length;
    const progressPercent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

    roadmap.progress = progressPercent;
    await roadmap.save();

    // Sync with CareerProgress model
    const completedIds = allMilestones
      .filter((m) => m.completed || m.status === 'Completed & Verified' || m.status === 'Completed — Review Recommended')
      .map((m) => m.id);

    await CareerProgress.findOneAndUpdate(
      { userId: userObjectId },
      {
        selectedCareer: roadmap.careerTitle,
        completedMilestones: completedIds,
        totalMilestones: totalCount,
        lastActivity: new Date(),
      },
      { upsert: true }
    );

    return roadmap;
  }

  /**
   * Helper to count total milestones in roadmap stages.
   */
  private static countMilestones(stages: IRoadmapStage[]): number {
    let count = 0;
    stages.forEach((s) => {
      count += s.milestones.length;
    });
    return count;
  }

  /**
   * Calls Google Gemini model to construct a structured, detailed roadmap.
   */
  private static async generateRoadmapWithAi(
    pContext: any,
    career: any,
    match: any
  ): Promise<IRoadmapStage[]> {
    const technicalSkills = pContext.skills?.technicalSkills || [];
    const softSkills = pContext.skills?.softSkills || [];
    const skillGaps = match.skillGaps.map((sg: string) => sg.replace(/^(Missing verified skill: |Missing career skill: |Missing skill: )/, ''));

    const userCountry = pContext.location?.country || 'Not specified';
    const userRegion = pContext.location 
      ? `${pContext.location.city || ''}, ${pContext.location.state || ''}, ${pContext.location.country || ''}`.trim().replace(/^,\s*/, '') 
      : 'Not specified';

    const systemPrompt = `You are a professional, detailed Career Coach.
Generate a highly personalized, structured Career Development Roadmap for the target career: "${career.title}" (Category: "${career.category}").
User Profile:
- Stream/Discipline: ${pContext.discipline}
- Specialization: ${pContext.specialization || 'None'}
- Education Level: ${pContext.educationLevel}
- Dream Career: ${pContext.dreamCareer}
- User Location: ${userRegion}
- Existing Skills: ${[...technicalSkills, ...softSkills].join(', ') || 'None specified'}
- Identified Skill Gaps for this Career: ${skillGaps.join(', ') || 'None'}

Instructions:
1. Generate multiple stages (minimum 5, maximum 7) representing a detailed development lifecycle:
   Foundation -> Core Knowledge -> Required Skills -> Tools/Tech -> Practice & Experience -> Certifications (if relevant) -> Career Readiness & Placement.
2. The roadmap must NOT be limited to a basic 3-4 milestone template. Provide a total of 10 to 15 highly meaningful milestones across the stages.
3. Personalize:
   - Identify which milestones correspond to the user's existing skills and mark them as strengths.
   - Inject tasks to learn and bridge the identified "Skill Gaps" directly into appropriate milestones.
4. Each milestone must contain:
   - "id": unique string identifier (e.g. "stage1_intro", "stage2_git")
   - "title": concise milestone title
   - "description": 2-3 sentences explaining the milestones
   - "skills": array of skills trained or validated (e.g. ["Python", "Algorithms"])
   - "tasks": array of 3-5 concrete study tasks (if related to a gap, prefix with "[Bridge Gap] ")
   - "activities": array of 1-2 practical activities or mini-projects (e.g. "Build a calculator", "Do clinical mock exam")
   - "learningObjectives": array of 2-3 learning goals
   - "dependencies": array of prerequisite milestone IDs
   - "completed": false
5. Region and Country Awareness: Do not assume the user is based in the United States or follows the US education/career licensing system. Adapt any regulatory checkpoints, licensing exams (e.g. USMLE, COMLEX for medical; bar exams for law; state licenses), and academic stages directly to the user's country: "${userCountry}". If the country is not specified or is outside the major jurisdiction, provide neutral international standards instead of forcing US-specific milestones.
6. JSON Output Requirements:
   - You must respond ONLY with a valid JSON object matching the schema below.
   - Do NOT include markdown code blocks (e.g. \`\`\`json ... \`\`\`), HTML tags, or any other explanations.
   - Ensure the JSON is properly closed and valid.

JSON Schema:
{
  "stages": [
    {
      "title": "Stage Title",
      "milestones": [
        {
          "id": "string",
          "title": "string",
          "description": "string",
          "skills": ["string"],
          "tasks": ["string"],
          "activities": ["string"],
          "learningObjectives": ["string"],
          "dependencies": ["string"],
          "completed": false
        }
      ]
    }
  ]
}`;

    const modelName = 'gemini-3.5-flash-lite';
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${config.GEMINI_API_KEY}`;

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [
          { role: 'user', parts: [{ text: `Generate a detailed personalized career roadmap for a ${career.title}.` }] }
        ],
        systemInstruction: {
          parts: [{ text: systemPrompt }]
        }
      }),
    });

    if (!response.ok) {
      throw new Error(`Gemini API returned status ${response.status}`);
    }

    const data: any = await response.json();
    let text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
      throw new Error('Empty response from Gemini.');
    }

    // Clean up JSON block markers if Gemini returned them despite system prompt
    text = text.trim();
    if (text.startsWith('```')) {
      text = text.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    }

    const parsed = JSON.parse(text);
    if (!parsed || !Array.isArray(parsed.stages)) {
      throw new Error('Invalid JSON structure returned by Gemini.');
    }

    return parsed.stages;
  }

  /**
   * Generates a detailed, deterministic, personalized fallback roadmap based on the career category.
   */
  private static generateDeterministicRoadmap(
    pContext: any,
    career: any,
    match: any
  ): IRoadmapStage[] {
    const technicalSkills = pContext.skills?.technicalSkills || [];
    const softSkills = pContext.skills?.softSkills || [];
    const userSkills = [...technicalSkills, ...softSkills].map((s) => s.toLowerCase());
    
    // Extract gaps
    const gaps: string[] = match.skillGaps.map((sg: string) => sg.replace(/^(Missing verified skill: |Missing career skill: |Missing skill: )/, ''));

    // Check if a skill is an existing strength
    const isStrength = (skill: string) => userSkills.some(us => us === skill.toLowerCase() || skill.toLowerCase().includes(us) || us.includes(skill.toLowerCase()));

    // Customize tasks based on user skills vs gaps
    const getSkillTask = (skill: string, defaultTask: string): string => {
      if (isStrength(skill)) {
        return `[Existing Strength] Apply your verified skill in ${skill} to accelerate this step.`;
      }
      if (gaps.some(g => g.toLowerCase() === skill.toLowerCase() || skill.toLowerCase().includes(g.toLowerCase()))) {
        return `[Bridge Gap] prioritized: Study and acquire necessary core knowledge in ${skill}.`;
      }
      return defaultTask;
    };

    const category = career.category.toLowerCase();
    
    // Choose appropriate roadmap structure
    if (category.includes('health') || category.includes('med')) {
      return this.getHealthcareRoadmap(career, getSkillTask, gaps);
    } else if (category.includes('eng') || category.includes('architect')) {
      return this.getEngineeringRoadmap(career, getSkillTask, gaps);
    } else if (category.includes('business') || category.includes('finance') || category.includes('account')) {
      return this.getBusinessRoadmap(career, getSkillTask, gaps);
    } else if (category.includes('art') || category.includes('design') || category.includes('media')) {
      return this.getCreativeRoadmap(career, getSkillTask, gaps);
    } else {
      return this.getGeneralRoadmap(career, getSkillTask, gaps);
    }
  }

  /* --- Category Specific Deterministic Roadmap Templates (Highly detailed, 6 stages, ~10-12 milestones) --- */

  private static getHealthcareRoadmap(career: any, getSkillTask: any, gaps: string[]): IRoadmapStage[] {
    const title = career.title;
    return [
      {
        title: 'Stage 1: Scientific Foundations',
        milestones: [
          {
            id: 'hc_1_1',
            title: 'Anatomy & Physiology Essentials',
            description: 'Master the structures and mechanical systems of the human body.',
            skills: ['Biology', 'Anatomy', 'Physiology'],
            tasks: [
              'Study human skeletal, muscular, and organ system charts',
              'Complete introductory biology lab modules',
              getSkillTask('Biology', 'Complete baseline assessments in cellular biology')
            ],
            activities: ['Dissect virtual anatomy model simulation'],
            learningObjectives: ['Define the 11 major organ systems', 'Correlate anatomical structures with physiological functions'],
            dependencies: [],
            completed: false
          },
          {
            id: 'hc_1_2',
            title: 'Biochemistry & Pharmacology Principles',
            description: 'Learn the molecular basis of cellular activity and response to chemical compounds.',
            skills: ['Chemistry', 'Pharmacology', 'Biochemistry'],
            tasks: [
              'Understand metabolic pathways and enzymatic actions',
              'Study drug classifications and pharmacokinetics principles',
              getSkillTask('Pharmacology', 'Memorize the top 100 clinical drug categories')
            ],
            activities: ['Simulate biochemical pathway analysis exercises'],
            learningObjectives: ['Outline basic enzymatic reactions', 'Describe drug absorption and excretion stages'],
            dependencies: ['hc_1_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 2: Core Medical Theory',
        milestones: [
          {
            id: 'hc_2_1',
            title: 'Clinical Pathology & Diagnostics',
            description: 'Identify mechanisms of disease states and the laboratory methods used to evaluate them.',
            skills: ['Clinical Diagnosis', 'Pathology'],
            tasks: [
              getSkillTask('Clinical Diagnosis', 'Bridge Gap: Learn diagnostic testing protocols'),
              'Examine blood smears and tissue biopsy slides virtually',
              'Study normal ranges for standard hematology and metabolic panels'
            ],
            activities: ['Diagnose three clinical patient case-studies'],
            learningObjectives: ['Differentiate viral and bacterial pathological signs', 'Interpret standard laboratory panels'],
            dependencies: ['hc_1_2'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 3: Patient Care & Clinical Skills',
        milestones: [
          {
            id: 'hc_3_1',
            title: 'Patient Care & Physical Assessments',
            description: 'Master the skills of checking vital signs, record-taking, and clinical communication.',
            skills: ['Patient Care', 'Communication'],
            tasks: [
              getSkillTask('Patient Care', 'Practice patient history taking processes'),
              getSkillTask('Communication', 'Exercise active listening and empathetic dialogue patterns'),
              'Learn standard documentation using electronic health records (EHR)'
            ],
            activities: ['Conduct mock patient history taking simulation'],
            learningObjectives: ['Perform physical assessments accurately', 'Document clinical observations using SOAP format'],
            dependencies: ['hc_2_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 4: Specialized Methods & Workflows',
        milestones: [
          {
            id: 'hc_4_1',
            title: 'Critical Thinking & Decision Making',
            description: 'Develop rapid triage, diagnosis, and ethical healthcare decision frameworks.',
            skills: ['Critical Thinking', 'Clinical Ethics'],
            tasks: [
              getSkillTask('Critical Thinking', 'Examine diagnostic error prevention models'),
              'Review medical ethics codes, patient privacy laws, and HIPAA rules',
              'Understand emergency medical triage algorithms'
            ],
            activities: ['Solve emergency room simulator scenarios'],
            learningObjectives: ['Apply ethical guidelines to critical patient cases', 'Formulate diagnosis plans under pressure'],
            dependencies: ['hc_3_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 5: Practical Internships & Rotations',
        milestones: [
          {
            id: 'hc_5_1',
            title: 'Clinical Rotations & Team Coordination',
            description: 'Apply medical theory in active clinical spaces alongside a healthcare team.',
            skills: ['Teamwork', 'Clinical Practice'],
            tasks: [
              getSkillTask('Teamwork', 'Practice handover communication with nursing teams'),
              'Shadow licensed professionals in outpatient and inpatient settings',
              'Participate in patient care rounds and medical case review discussions'
            ],
            activities: ['Complete supervised bedside clinical exercises'],
            learningObjectives: ['Integrate into multidisciplinary clinical teams', 'Safely conduct patient checks under supervision'],
            dependencies: ['hc_4_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 6: Professional Licensure & Readiness',
        milestones: [
          {
            id: 'hc_6_1',
            title: 'Licensing Examination Preparation',
            description: 'Study for official licensing exams required to practice medicine in this region.',
            skills: ['Medicine', 'Licensing Prep'],
            tasks: [
              'Complete comprehensive medical board practice tests',
              'Identify target local state licensing and board requirements',
              'Assemble academic credentials and internship records for review'
            ],
            activities: ['Take a full-length mock board examination'],
            learningObjectives: ['Identify knowledge gaps in final board topics', 'Ensure compliance with regional medical standards'],
            dependencies: ['hc_5_1'],
            completed: false
          },
          {
            id: 'hc_6_2',
            title: 'Healthcare Placement & Resume Prep',
            description: 'Build a strong clinical CV and apply for residency programs or clinical jobs.',
            skills: ['Presentation', 'Writing'],
            tasks: [
              'Draft a medical CV showing completed rotations, skills, and certifications',
              'Prepare clinical case discussion records for potential interviews',
              'Practice mock healthcare behavioral interview questions'
            ],
            activities: ['Create polished medical professional portfolio'],
            learningObjectives: ['Successfully communicate clinical experience in interviews', 'Align CV with hospital priorities'],
            dependencies: ['hc_6_1'],
            completed: false
          }
        ]
      }
    ];
  }

  private static getEngineeringRoadmap(career: any, getSkillTask: any, gaps: string[]): IRoadmapStage[] {
    const title = career.title;
    return [
      {
        title: 'Stage 1: Scientific & Math Foundations',
        milestones: [
          {
            id: 'eng_1_1',
            title: 'Advanced Mathematics & Calculations',
            description: 'Master calculus, linear algebra, and differential equations for engineering calculations.',
            skills: ['Math', 'Analytical Thinking'],
            tasks: [
              'Review matrix transformations and numerical methods',
              getSkillTask('Analytical Thinking', 'Analyze structural load equations'),
              'Solve systems of linear equations for mechanical models'
            ],
            activities: ['Solve a set of 20 engineering calculation problems'],
            learningObjectives: ['Apply differentiation and integration to physical systems', 'Interpret analytical statistics'],
            dependencies: [],
            completed: false
          },
          {
            id: 'eng_1_2',
            title: 'Engineering Physics & Dynamics',
            description: 'Study vectors, mechanics, electrical charges, and thermodynamic properties.',
            skills: ['Physics', 'Problem Solving'],
            tasks: [
              'Analyze force diagrams, moments, and friction forces',
              getSkillTask('Problem Solving', 'Bridge Gap: Practice engineering physics analysis'),
              'Understand fluid mechanics and electrical circuit theories'
            ],
            activities: ['Model mechanical force behaviors in virtual sandbox simulation'],
            learningObjectives: ['Draw precise free-body diagrams', 'Evaluate material stress/strain behaviors'],
            dependencies: ['eng_1_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 2: CAD & Digital Modeling',
        milestones: [
          {
            id: 'eng_2_1',
            title: 'Computer-Aided Design (CAD) Core',
            description: 'Learn drafting software to model components, systems, and structures.',
            skills: ['CAD', 'AutoCAD', 'SolidWorks', 'Revit'],
            tasks: [
              getSkillTask('CAD', 'Bridge Gap: Design models in CAD'),
              getSkillTask('AutoCAD', 'Develop 2D technical drawings'),
              getSkillTask('SolidWorks', 'Build 3D models and assembly components in SolidWorks')
            ],
            activities: ['Draft a detailed 3D assembly blueprint of a physical connector'],
            learningObjectives: ['Generate engineering blueprints matching industry regulations', 'Construct multi-part CAD assemblies'],
            dependencies: ['eng_1_2'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 3: Advanced Domain Skills',
        milestones: [
          {
            id: 'eng_3_1',
            title: 'Systems & Control Engineering',
            description: 'Develop custom logic, simulations, and instrumentation models.',
            skills: ['MATLAB', 'PLC', 'Circuit Design'],
            tasks: [
              getSkillTask('MATLAB', 'Write control systems simulations in MATLAB'),
              getSkillTask('PLC', 'Bridge Gap: Program programmable logic controllers (PLC)'),
              getSkillTask('Circuit Design', 'Develop circuit designs matching load requirements')
            ],
            activities: ['Construct a virtual control circuit loop simulation'],
            learningObjectives: ['Write PLC ladder logic codes', 'Apply feedback controls to mechanical designs'],
            dependencies: ['eng_2_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 4: Engineering Tools & Standards',
        milestones: [
          {
            id: 'eng_4_1',
            title: 'Project Management & Quality Standards',
            description: 'Understand engineering project scopes, budgets, and ISO quality guidelines.',
            skills: ['Project Management', 'ISO Standards'],
            tasks: [
              getSkillTask('Project Management', 'Bridge Gap: Practice engineering project management'),
              'Review OSHA occupational safety guidelines and ISO standards',
              'Draft a project timeline Gantt chart with task dependencies'
            ],
            activities: ['Prepare project budget analysis sheet for building component'],
            learningObjectives: ['Explain ISO 9001 and environmental safety rules', 'Plan project resource timelines'],
            dependencies: ['eng_3_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 5: Hands-on Projects & Practical Experience',
        milestones: [
          {
            id: 'eng_5_1',
            title: 'Capstone Design Project',
            description: 'Build and validate a real-world prototype or structural design project.',
            skills: ['Creativity', 'Teamwork', 'Project Management'],
            tasks: [
              'Define prototype specs and engineering requirements',
              'Construct, wire, or build design components',
              'Run stress testing and collect validation metrics'
            ],
            activities: ['Assemble and test prototype model project'],
            learningObjectives: ['Troubleshoot and fix prototype defects', 'Document validation findings in technical report'],
            dependencies: ['eng_4_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 6: Professional Certification & Careers',
        milestones: [
          {
            id: 'eng_6_1',
            title: 'Professional Licensing Preparation',
            description: 'Study for FE / PE examinations or equivalent local engineering license.',
            skills: ['Engineering', 'Licensure Prep'],
            tasks: [
              'Complete FE exam prep questions and review guides',
              'Identify target local state licensing rules and board filings',
              'Assemble coursework credentials for review'
            ],
            activities: ['Complete FE simulation mock practice examination'],
            learningObjectives: ['Identify knowledge gaps in final licensing topics', 'Meet regional regulatory standards'],
            dependencies: ['eng_5_1'],
            completed: false
          },
          {
            id: 'eng_6_2',
            title: 'Engineering Interview & Portfolio Review',
            description: 'Assemble your design portfolio and prepare for technical interviews.',
            skills: ['Presentation', 'Writing'],
            tasks: [
              'Assemble technical drawings and photos of capstone design in portfolio',
              'Prepare descriptions explaining design decisions',
              'Practice mock system analysis and behavioral engineering interview questions'
            ],
            activities: ['Conduct mock engineering whiteboard interview practice'],
            learningObjectives: ['Confidently explain engineering designs in interviews', 'Organize project portfolio layout'],
            dependencies: ['eng_6_1'],
            completed: false
          }
        ]
      }
    ];
  }

  private static getBusinessRoadmap(career: any, getSkillTask: any, gaps: string[]): IRoadmapStage[] {
    const title = career.title;
    return [
      {
        title: 'Stage 1: Business & Economic Foundations',
        milestones: [
          {
            id: 'bus_1_1',
            title: 'Introduction to Economics & Markets',
            description: 'Understand micro and macroeconomics, market indicators, and corporate business patterns.',
            skills: ['Math', 'Analytical Thinking'],
            tasks: [
              'Study supply/demand curve modeling and pricing metrics',
              getSkillTask('Analytical Thinking', 'Analyze current market economic reports'),
              'Understand interest rates, inflation, and fiscal policies'
            ],
            activities: ['Draft a market dynamics summary report for a selected industry'],
            learningObjectives: ['Describe how supply/demand drives pricing', 'Analyze economic indicators affecting business cycles'],
            dependencies: [],
            completed: false
          },
          {
            id: 'bus_1_2',
            title: 'Accounting Fundamentals',
            description: 'Learn double-entry bookkeeping, ledger entries, and financial statements.',
            skills: ['Accounting', 'Finance'],
            tasks: [
              getSkillTask('Accounting', 'Bridge Gap: Master standard accounting principles'),
              'Study balance sheets, income statements, and cash flow reports',
              'Understand general ledger journals and adjusting entries'
            ],
            activities: ['Balance a mock company ledger sheet and prepare statements'],
            learningObjectives: ['Differentiate between assets, liabilities, and equity', 'Analyze financial statements for health indicators'],
            dependencies: ['bus_1_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 2: Core Analytical Tools',
        milestones: [
          {
            id: 'bus_2_1',
            title: 'Financial Analysis & Business Software',
            description: 'Master spreadsheet applications and database systems for business analysis.',
            skills: ['Excel', 'SAP', 'Tally'],
            tasks: [
              getSkillTask('Excel', 'Learn VLOOKUP, pivot tables, and financial formula writing in Excel'),
              getSkillTask('SAP', 'Bridge Gap: Learn data reporting in SAP'),
              getSkillTask('Tally', 'Input accounting entries in Tally')
            ],
            activities: ['Build an Excel template calculating cash flow models'],
            learningObjectives: ['Construct dynamic spreadsheets for business planning', 'Generate business reports using SAP/Tally'],
            dependencies: ['bus_1_2'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 3: Advanced Business Management',
        milestones: [
          {
            id: 'bus_3_1',
            title: 'Corporate Strategy & Leadership',
            description: 'Learn business strategies, product management, and team collaboration guidelines.',
            skills: ['Business Strategy', 'Leadership', 'Negotiation'],
            tasks: [
              getSkillTask('Business Strategy', 'Bridge Gap: Master corporate strategy analysis'),
              getSkillTask('Leadership', 'Study leadership styles and conflict resolution'),
              getSkillTask('Negotiation', 'Practice negotiation methods and contract review guidelines')
            ],
            activities: ['Conduct a mock corporate negotiation case-study simulation'],
            learningObjectives: ['Conduct SWOT analysis on competitor firms', 'Apply leadership principles in business scenarios'],
            dependencies: ['bus_2_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 4: Operations & Sales/Marketing',
        milestones: [
          {
            id: 'bus_4_1',
            title: 'Marketing Campaigns & Supply Chain',
            description: 'Understand customer acquisition channels, digital ads, and logistic structures.',
            skills: ['Marketing', 'Digital Marketing', 'Sales', 'Supply Chain'],
            tasks: [
              getSkillTask('Marketing', 'Bridge Gap: Design product marketing strategies'),
              getSkillTask('Digital Marketing', 'Set up SEO and digital ad campaign metrics'),
              getSkillTask('Supply Chain', 'Examine supply chain logistics and shipping routes')
            ],
            activities: ['Prepare digital ad budget plan sheet for product launch'],
            learningObjectives: ['Calculate customer acquisition cost (CAC)', 'Identify bottlenecks in supply chain logistics'],
            dependencies: ['bus_3_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 5: Applied Projects & Cases',
        milestones: [
          {
            id: 'bus_5_1',
            title: 'Comprehensive Business Plan Case Study',
            description: 'Develop a complete product plan or business proposal from scratch.',
            skills: ['Communication', 'Project Management', 'Presentation'],
            tasks: [
              'Identify target customer segments and product market fit',
              'Develop NPV/IRR financial spreadsheets projecting sales',
              'Draft executive brief explaining product differentiator factors'
            ],
            activities: ['Present business plan pitch deck to classmates or advisors'],
            learningObjectives: ['Synthesize finance, marketing, and strategy in business plan', 'Defend plan assumptions in mock presentations'],
            dependencies: ['bus_4_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 6: Professional Readiness & Networking',
        milestones: [
          {
            id: 'bus_6_1',
            title: 'Certifications & Mock Placement Interviews',
            description: 'Complete target business qualifications and prepare for placement interviews.',
            skills: ['Business Analysis', 'Interview Prep'],
            tasks: [
              'Complete CFA / CA / MBA prep practice questions',
              'Build a comprehensive professional network profile (e.g. LinkedIn)',
              'Practice mock consulting case-interviews and technical finance questions'
            ],
            activities: ['Conduct mock case interview practice'],
            learningObjectives: ['Identify knowledge gaps in licensing topics', 'Successfully answer consulting business cases'],
            dependencies: ['bus_5_1'],
            completed: false
          }
        ]
      }
    ];
  }

  private static getCreativeRoadmap(career: any, getSkillTask: any, gaps: string[]): IRoadmapStage[] {
    const title = career.title;
    return [
      {
        title: 'Stage 1: Creative & Artistic Foundations',
        milestones: [
          {
            id: 'cr_1_1',
            title: 'Visual Arts & Styling Principles',
            description: 'Learn color theory, composition rules, lighting styles, and perspective drawing.',
            skills: ['Creativity', 'Graphic Design'],
            tasks: [
              'Review color palettes, gradients, and contrasting systems',
              getSkillTask('Creativity', 'Practice sketching layout mockups'),
              getSkillTask('Graphic Design', 'Bridge Gap: Master visual typography systems')
            ],
            activities: ['Draft a physical storyboard or sketch matching layout guidelines'],
            learningObjectives: ['Apply visual rules to design layouts', 'Differentiate between serif and sans-serif typeface usage'],
            dependencies: [],
            completed: false
          },
          {
            id: 'cr_1_2',
            title: 'Introduction to Creative Software',
            description: 'Learn vector and raster editing platforms for image, document, or audio assets.',
            skills: ['Figma', 'Blender', 'Photoshop'],
            tasks: [
              getSkillTask('Figma', 'Build vector shapes and component layouts in Figma'),
              getSkillTask('Blender', 'Bridge Gap: Design 3D geometric meshes in Blender'),
              'Learn photo restoration tools in digital imaging software'
            ],
            activities: ['Assemble a digital layout board showcasing asset styles'],
            learningObjectives: ['Differentiate vector vs raster file exports', 'Perform basic 3D mesh translations in Blender'],
            dependencies: ['cr_1_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 2: Core Domain Workflows',
        milestones: [
          {
            id: 'cr_2_1',
            title: 'Interactive Design & Interface Assets',
            description: 'Develop wireframes, interactive screen layouts, and component assets.',
            skills: ['UI/UX', 'Animation'],
            tasks: [
              getSkillTask('UI/UX', 'Bridge Gap: Design high-fidelity wireframes'),
              getSkillTask('Animation', 'Program basic timeline keyframe animations'),
              'Practice mobile app flow mapping and accessibility checks'
            ],
            activities: ['Create an interactive mobile screen flow prototype'],
            learningObjectives: ['Check layout contrast against WCAG contrast checks', 'Understand interactive screen state transitions'],
            dependencies: ['cr_1_2'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 3: Advanced Tools & Production Methods',
        milestones: [
          {
            id: 'cr_3_1',
            title: 'Digital Marketing & Content Creation',
            description: 'Study how to launch marketing campaigns and create video/image assets for target audiences.',
            skills: ['Digital Marketing', 'Video Editing', 'Content Creation'],
            tasks: [
              getSkillTask('Digital Marketing', 'Analyze social media audience metric reports'),
              getSkillTask('Video Editing', 'Cut and assemble raw footage clips in editing software'),
              getSkillTask('Content Creation', 'Bridge Gap: Plan engaging media content assets')
            ],
            activities: ['Produce a short 1-minute video explaining a product feature'],
            learningObjectives: ['Format video and audio for social channels', 'Analyze user click-through rate (CTR) telemetry'],
            dependencies: ['cr_2_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 4: Creative Client Work & Project Management',
        milestones: [
          {
            id: 'cr_4_1',
            title: 'Brief Interpretation & Client Communications',
            description: 'Learn how to analyze client design briefs, manage scope, and write revisions.',
            skills: ['Communication', 'Project Management', 'Negotiation'],
            tasks: [
              getSkillTask('Communication', 'Practice active listening in design revision simulation'),
              getSkillTask('Project Management', 'Build project timelines and milestones schedule'),
              getSkillTask('Negotiation', 'Review contracts and licensing rights rules')
            ],
            activities: ['Prepare project proposal response document for creative brief'],
            learningObjectives: ['Translate raw client feedback into technical specifications', 'Draft design contracts covering usage rights'],
            dependencies: ['cr_3_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 5: Portfolio Development',
        milestones: [
          {
            id: 'cr_5_1',
            title: 'Professional Portfolio Construction',
            description: 'Assemble your best creative pieces into a clean, public-facing visual portfolio site.',
            skills: ['Presentation', 'Writing', 'Creativity'],
            tasks: [
              'Select 3-5 major design projects showing diverse skillsets',
              'Write case-studies explaining the user research and design steps for each',
              'Launch a responsive portfolio layout showcase (e.g. Behance/GitHub)'
            ],
            activities: ['Publish your finished visual portfolio live'],
            learningObjectives: ['Structure case-studies to show complete problem-solving cycle', 'Ensure responsive mobile sizing for portfolio site'],
            dependencies: ['cr_4_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 6: Careers & Professional Networking',
        milestones: [
          {
            id: 'cr_6_1',
            title: 'Creative Placement & Interview Preparation',
            description: 'Prepare for placement assessments, creative reviews, and behavioral interviews.',
            skills: ['Interview Prep', 'Professional Ethics'],
            tasks: [
              'Practice talking through portfolio pieces in clear paragraphs',
              'Participate in mock portfolio critiques and interview reviews',
              'Set up professional networking profiles to reach design recruiters'
            ],
            activities: ['Conduct mock design whiteboard or case review practice'],
            learningObjectives: ['Defend design decisions in professional critiques', 'Confidently explain user flow rationale'],
            dependencies: ['cr_5_1'],
            completed: false
          }
        ]
      }
    ];
  }

  private static getGeneralRoadmap(career: any, getSkillTask: any, gaps: string[]): IRoadmapStage[] {
    const title = career.title;
    return [
      {
        title: 'Stage 1: Core Foundations',
        milestones: [
          {
            id: 'gen_1_1',
            title: 'Industry Fundamentals',
            description: 'Understand the basic systems, history, and roles inside this career path.',
            skills: ['Research', 'Analytical Thinking'],
            tasks: [
              'Read articles explaining key structures and trends in this field',
              getSkillTask('Research', 'Gather market reports on industry needs'),
              getSkillTask('Analytical Thinking', 'Analyze core career opportunities')
            ],
            activities: ['Draft a short 2-page report on current trends in this category'],
            learningObjectives: ['Outline key sub-disciplines', 'Identify major industry actors and regulators'],
            dependencies: [],
            completed: false
          },
          {
            id: 'gen_1_2',
            title: 'Core Concepts & Theories',
            description: 'Study introductory theoretical concepts that govern practice in this field.',
            skills: ['Writing', 'Communication'],
            tasks: [
              'Memorize key vocabulary and technical terminology',
              getSkillTask('Communication', 'Practice discussing core industry topics'),
              'Complete introductory academic study modules'
            ],
            activities: ['Write a glossary matching concepts with definitions'],
            learningObjectives: ['Define 20 core technical terms', 'Explain underlying frameworks'],
            dependencies: ['gen_1_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 2: Critical Tools & Soft Skills',
        milestones: [
          {
            id: 'gen_2_1',
            title: 'Primary Tools & Platforms',
            description: 'Learn to navigate standard software, platforms, or tools used daily in this career.',
            skills: ['Excel', 'Presentation'],
            tasks: [
              getSkillTask('Excel', 'Learn baseline reporting and analysis in spreadsheet applications'),
              getSkillTask('Presentation', 'Build presentation decks explaining trends'),
              'Study standard workflows for team collaboration software'
            ],
            activities: ['Create an Excel tracker sheet and summary deck for data metrics'],
            learningObjectives: ['Construct data dashboards', 'Present analytical reports to colleagues'],
            dependencies: ['gen_1_2'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 3: Specialized Skills',
        milestones: [
          {
            id: 'gen_3_1',
            title: 'Core Execution Skills',
            description: 'Acquire and practice the core hard skills required to perform key responsibilities.',
            skills: career.skills.slice(0, 3),
            tasks: [
              getSkillTask(career.skills[0] || 'Domain Skill', `Learn basic elements of ${career.skills[0] || 'the core skill'}`),
              getSkillTask(career.skills[1] || 'Domain Process', `Study workflow guidelines for ${career.skills[1] || 'the domain process'}`),
              'Review case studies showing implementation steps'
            ],
            activities: ['Complete practical exercises modeling core workflows'],
            learningObjectives: ['Complete tasks using standard techniques', 'Verify outputs match project requirements'],
            dependencies: ['gen_2_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 4: Practical Application & Small Projects',
        milestones: [
          {
            id: 'gen_4_1',
            title: 'Hands-on Practice Case Study',
            description: 'Apply your knowledge to solve real-world problems through simulated tasks.',
            skills: ['Problem Solving', 'Creativity'],
            tasks: [
              getSkillTask('Problem Solving', 'Deconstruct case briefs to find issues'),
              'Outline potential approaches based on domain frameworks',
              'Implement solutions and document the outcomes'
            ],
            activities: ['Solve case study project assignment'],
            learningObjectives: ['Apply academic models to practice scenarios', 'Assess alternative solution models'],
            dependencies: ['gen_3_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 5: Portfolio & Profile Preparation',
        milestones: [
          {
            id: 'gen_5_1',
            title: 'Portfolio Development',
            description: 'Compile case studies, drawings, or reports representing your skills in this field.',
            skills: ['Writing', 'Presentation'],
            tasks: [
              'Select 2-3 completed practice projects or essays',
              'Format items into cohesive digital slides or portfolio site',
              'Draft executive summaries explaining your work'
            ],
            activities: ['Create and publish public project portfolio online'],
            learningObjectives: ['Present complex work in clean layouts', 'Clearly explain personal project details'],
            dependencies: ['gen_4_1'],
            completed: false
          }
        ]
      },
      {
        title: 'Stage 6: Career Placement & Readiness',
        milestones: [
          {
            id: 'gen_6_1',
            title: 'Mock Interview Prep & Placement',
            description: 'Prepare your resume and practice behavioral questions to land internships or jobs.',
            skills: ['Interview Prep', 'Communication'],
            tasks: [
              'Draft a resume showing skills, education, and portfolio links',
              'Practice answering standard questions in paragraphs',
              'Review company research techniques and job matching options'
            ],
            activities: ['Conduct mock placement interviews with advisors or tools'],
            learningObjectives: ['Outline personal experiences using STAR format', 'Present key strengths during interviews'],
            dependencies: ['gen_5_1'],
            completed: false
          }
        ]
      }
    ];
  }

  /**
   * Calls Gemini to generate assessment questions with strict validation.
   */
  private static async generateAssessmentQuestionsWithAi(milestone: IMilestone, careerTitle: string): Promise<IQuestion[]> {
    const systemPrompt = `You are a professional certification exam developer.
Create a high-quality, milestone-specific review quiz for the milestone: "${milestone.title}" in the career path: "${careerTitle}".
Milestone context:
- Description: ${milestone.description}
- Skills: ${milestone.skills.join(', ')}
- Checkpoints/Tasks: ${milestone.tasks.join('; ')}
- Objectives: ${milestone.learningObjectives.join('; ')}

Instructions:
1. Generate exactly 5 high-quality, multiple-choice questions focusing on scenarios, concepts, or tools relevant to this milestone.
2. Avoid generic questions. Tailor them specifically to the skills (${milestone.skills.join(', ')}) and description.
3. Each question must contain:
   - "question": string question text (clear, concise, factual)
   - "options": array of exactly 4 choices (distinct, plausible, non-empty strings)
   - "correctAnswerIndex": number index of the correct choice (0, 1, 2, or 3)
4. Do NOT include markdown formatting blocks (like \`\`\`json), HTML tags, or any surrounding text. Respond ONLY with a valid JSON array of question objects.
5. Factual integrity: Do not invent false company requirements or fake statistics.

JSON Schema:
[
  {
    "question": "Question text?",
    "options": ["Choice A", "Choice B", "Choice C", "Choice D"],
    "correctAnswerIndex": 0
  }
]`;

    const modelName = 'gemini-3.5-flash-lite';
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${config.GEMINI_API_KEY}`;

    let response: Response;
    try {
      response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [
            { role: 'user', parts: [{ text: `Generate a 5-question milestone assessment for ${milestone.title}.` }] }
          ],
          systemInstruction: {
            parts: [{ text: systemPrompt }]
          }
        }),
        signal: AbortSignal.timeout(20000), // 20-second network timeout
      });
    } catch (fetchErr: any) {
      if (fetchErr?.name === 'TimeoutError' || fetchErr?.name === 'AbortError') {
        throw new Error('AI question generation request timed out. Please try again.');
      }
      throw new Error(`Failed to connect to AI assessment service: ${fetchErr?.message || 'Network error'}`);
    }

    if (!response.ok) {
      if (response.status === 429) {
        throw new Error('AI assessment service is temporarily busy (rate limit reached). Please try again shortly.');
      }
      if (response.status === 403 || response.status === 401) {
        throw new Error('AI assessment service authentication failed. Please check Gemini API key configuration.');
      }
      throw new Error(`AI assessment service responded with status ${response.status}`);
    }

    const data: any = await response.json();
    let text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text || typeof text !== 'string') {
      throw new Error('Empty or invalid response received from AI assessment service.');
    }

    text = text.trim();
    if (text.startsWith('```')) {
      text = text.replace(/^```json\s*/i, '').replace(/^```\s*/, '').replace(/```$/g, '').trim();
    }

    let parsed: any;
    try {
      parsed = JSON.parse(text);
    } catch (_parseErr) {
      throw new Error('Malformed JSON received from AI assessment service.');
    }

    if (!Array.isArray(parsed)) {
      throw new Error('Invalid assessment structure: Expected a JSON array of questions.');
    }

    // Strict validation and sanitization of each question item
    const validatedQuestions: IQuestion[] = [];
    for (const item of parsed) {
      if (!item || typeof item !== 'object') continue;

      const questionText = typeof item.question === 'string' ? item.question.trim() : '';
      if (questionText.length < 8) continue;

      if (!Array.isArray(item.options) || item.options.length < 2) continue;
      const cleanOptions = item.options
        .map((opt: any) => (typeof opt === 'string' ? opt.trim() : ''))
        .filter((opt: string) => opt.length > 0);

      // Check for distinct choices
      const uniqueOptions = new Set(cleanOptions.map((opt: string) => opt.toLowerCase()));
      if (cleanOptions.length < 2 || uniqueOptions.size !== cleanOptions.length) continue;

      const answerIdx = item.correctAnswerIndex;
      if (
        typeof answerIdx !== 'number' ||
        !Number.isInteger(answerIdx) ||
        answerIdx < 0 ||
        answerIdx >= cleanOptions.length
      ) {
        continue;
      }

      validatedQuestions.push({
        question: questionText,
        options: cleanOptions,
        correctAnswerIndex: answerIdx,
      });
    }

    if (validatedQuestions.length < 3) {
      throw new Error(
        `AI generated insufficient valid questions (${validatedQuestions.length} valid out of ${parsed.length} received).`
      );
    }

    return validatedQuestions;
  }

  /**
   * Calls Gemini to generate standalone skill assessment questions with strict validation.
   */
  private static async generateSkillQuestionsWithAi(
    skillName: string,
    domain: string,
    difficulty: SkillDifficulty
  ): Promise<IQuestion[]> {
    const systemPrompt = `You are a professional technical skills assessor and certification author.
Create a high-quality, practical multiple-choice skill assessment for the technical skill: "${skillName}" (Domain/Field: "${domain}", Proficiency Level: "${difficulty}").

Instructions:
1. Generate exactly 5 high-quality, multiple-choice questions testing core concepts, syntax/rules, best practices, real-world application, and troubleshooting of ${skillName} at a ${difficulty} level.
2. Avoid generic filler questions. Tailor questions specifically to "${skillName}".
3. Each question must contain:
   - "question": string question text (clear, unambiguous, factual)
   - "options": array of exactly 4 choices (distinct, plausible, non-empty strings)
   - "correctAnswerIndex": number index of the correct choice (0, 1, 2, or 3)
4. Do NOT include markdown blocks (like \`\`\`json), HTML tags, or any explanatory commentary. Respond ONLY with a valid JSON array matching the schema.
5. Factual integrity: Ensure technical correctness and accuracy.

JSON Schema:
[
  {
    "question": "Question text?",
    "options": ["Choice A", "Choice B", "Choice C", "Choice D"],
    "correctAnswerIndex": 0
  }
]`;

    const modelName = 'gemini-3.5-flash-lite';
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${config.GEMINI_API_KEY}`;

    let response: Response;
    try {
      response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [
            { role: 'user', parts: [{ text: `Generate a 5-question ${difficulty} skill assessment for ${skillName}.` }] }
          ],
          systemInstruction: {
            parts: [{ text: systemPrompt }]
          }
        }),
        signal: AbortSignal.timeout(20000),
      });
    } catch (fetchErr: any) {
      if (fetchErr?.name === 'TimeoutError' || fetchErr?.name === 'AbortError') {
        throw new Error('AI question generation request timed out. Please try again.');
      }
      throw new Error(`Failed to connect to AI assessment service: ${fetchErr?.message || 'Network error'}`);
    }

    if (!response.ok) {
      if (response.status === 429) {
        throw new Error('AI assessment service is temporarily busy (rate limit reached). Please try again shortly.');
      }
      if (response.status === 403 || response.status === 401) {
        throw new Error('AI assessment service authentication failed. Please check Gemini API key configuration.');
      }
      throw new Error(`AI assessment service responded with status ${response.status}`);
    }

    const data: any = await response.json();
    let text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text || typeof text !== 'string') {
      throw new Error('Empty or invalid response received from AI assessment service.');
    }

    text = text.trim();
    if (text.startsWith('```')) {
      text = text.replace(/^```json\s*/i, '').replace(/^```\s*/, '').replace(/```$/g, '').trim();
    }

    let parsed: any;
    try {
      parsed = JSON.parse(text);
    } catch (_parseErr) {
      throw new Error('Malformed JSON received from AI assessment service.');
    }

    if (!Array.isArray(parsed)) {
      throw new Error('Invalid assessment structure: Expected a JSON array of questions.');
    }

    const validatedQuestions: IQuestion[] = [];
    for (const item of parsed) {
      if (!item || typeof item !== 'object') continue;

      const questionText = typeof item.question === 'string' ? item.question.trim() : '';
      if (questionText.length < 8) continue;

      if (!Array.isArray(item.options) || item.options.length < 2) continue;
      const cleanOptions = item.options
        .map((opt: any) => (typeof opt === 'string' ? opt.trim() : ''))
        .filter((opt: string) => opt.length > 0);

      const uniqueOptions = new Set(cleanOptions.map((opt: string) => opt.toLowerCase()));
      if (cleanOptions.length < 2 || uniqueOptions.size !== cleanOptions.length) continue;

      const answerIdx = item.correctAnswerIndex;
      if (
        typeof answerIdx !== 'number' ||
        !Number.isInteger(answerIdx) ||
        answerIdx < 0 ||
        answerIdx >= cleanOptions.length
      ) {
        continue;
      }

      validatedQuestions.push({
        question: questionText,
        options: cleanOptions,
        correctAnswerIndex: answerIdx,
      });
    }

    if (validatedQuestions.length < 3) {
      throw new Error(
        `AI generated insufficient valid questions for ${skillName} (${validatedQuestions.length} valid out of ${parsed.length} received).`
      );
    }

    return validatedQuestions;
  }
}
